config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index]

  resources :restaurants, except: [:show]

  resources :restaurants, only: [:show] do
    resources :visits, only: [:create]
    resources :bookmarks, only: [:create]
  end


  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  resources :visits, only: [:update, :destroy]

  resources :users, only: [] do
    resources :follows, only: [:create]
  end

  resources :follows, only: [:index, :destroy]
  resources :bookmarks, only: [:index, :destroy]
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :reviews
  # UNCOMMENT THE VALIDATIONS BELOW LATER IN THE PROJECT
  validates :date, presence: true
  validates :user, presence: true
  validates :restaurant, presence: true
  # Note: have not included number_of_people in validations - consider whether to do so
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    visits = Visit.where(user: current_user)

    @upcoming_visits = visits.select { |v| v.date > Date.today }.sort_by { |v| v[:created_at] }.reverse
    @previous_visits = visits.select { |v| v.date <= Date.today }.sort_by { |v| v[:date] }.reverse

    followings_id = Follow.where(follower_id: current_user.id).map { |user| user.following_id }
    @followings_visits = followings_id.map { |id| Visit.where(user_id: id) }.flatten

    @restaurants = visits.map { |v| v.restaurant }
    # @review_hash_array = []
    # @previous_visits.each do |previous_visit|
    #   review = Review.find_by(visit_id: previous_visit.id)
    #   if previous_visit.reviews.any?
    #     review_hash = {
    #       review_content: review.content,
    #       review_rating: review.rating,
    #       review_id: review.id,
    #       review_date: review.created_at.strftime("%d/%m/%y"),
    #       visit: previous_visit,
    #       review_included: true
    #     }
    #   else
    #     review_hash = {
    #       review: "none",
    #       visit: previous_visit,
    #       review_included: false
    #     }
    #   end
    #   @review_hash_array << review_hash
    # end
    # @previous_visits = @previous_visits.sort_by { |v| v[:date] }.reverse

    # @restaurants = []
    # @visits.map do |visit|
    #   restaurant = Restaurant.find(visit.restaurant_id)
    #   @restaurants << restaurant
    # end

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "restaurants/info_window", locals: { restaurant: restaurant }),
      }
    end
  end

  def create
    @visit = Visit.new(visit_params)
    @visit.date = Date.parse params[:visit][:date]
    @visit.user_id = current_user.id
    @visit.restaurant = Restaurant.find(params[:restaurant_id])
    if @visit.save
      flash[:notice] = "Booking successfully created"
    else
      raise
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      redirect_to restaurant_path(restaurant)
    end
  end

  def edit
  end

  def update
    if @visit.update(visit_params)
      flash[:notice] = "Visit successfully updated"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      render :edit
    end
  end

  def destroy
    visit = Visit.find(params[:id])
    if visit.destroy
      flash[:notice] = "Upcoming meal successfully removed."
      redirect_to visits_path
    else
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      render :index
    end
  end

  private

  def visit_params
    params.require(:visit).permit(:number_of_people, :restaurant_id)
  end
end

app/views/visits/_modal_restaurant_reviews.html.erb
  <div class="modal fade" id="visitsModalReviews<%= restaurant.id %>" tabindex="-1" role="dialog" aria-labelledby="visitsModalReviewsTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="title_and_rating">
          <div class="modal-header-and-stars"> <h5 class="modal-title " id="visits ModalReviewsTitle"><%= restaurant.name %></h5>
            <div class="star-container">
              <% count_gold = restaurant.total_rating %>
              <% count_grey = (5 - count_gold) %>
              <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
              <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
            </div>
          </div>
        </div>
        <div class="modal-header d-flex flex-column">
          <p><%= restaurant.address %>, <%= restaurant.city %></p>
          <div class="modal-review-details">
          </div>
        </div>
        <% followings_visits.select { |v| v.restaurant_id == restaurant.id }.each do |v| %>

          <div class="modal-body" style="font-size: 16px">
            <% if !v.reviews.first.nil? %>
              <p> <u> <%= v.user.first_name %> <%= v.user.last_name %></u>. Visited on: <%= v.date.strftime("%d/%m/%y") %> |
              Review from: <%= v.reviews.first.created_at.strftime("%d/%m/%y") %></p>
              <em>"<%= v.reviews.first.content %>"</em>
            <% end %>
        </div>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

app/views/visits/_previous_visit_card.html.erb
<div class="restaurant_card">
  <div class="restaurant_card_carousel">
    <%= render 'shared/restaurant_carousel_visit', locals: { :visit => visit, :restaurant => visit.restaurant } %>
  </div>
  <div class="restaurant_card_info">

    <div class="restaurant_info_strip">
      <h2><%= link_to visit.restaurant.name, restaurant_path(visit.restaurant) %></h2>
    </div>

    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("category.svg") %> <%= visit.restaurant.category %>
      </p>
    </div>

    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("city.svg")%> <%= visit.restaurant.city%> <br>
        <%= image_tag("address.svg") %> <%= visit.restaurant.address%> <br>
        <%= image_tag("people.svg") %> <%= visit.number_of_people %> <br>
        <%= image_tag("calendar.svg") %> <%= visit.date.strftime("%d/%m/%y") %> <br>
      </p>
    </div>

    <div class="buttons-info" style="justify-content: center; align-items: center;">
      <% if visit.reviews.first.nil? %>
        <%= link_to 'Write Review', new_visit_review_path(visit), class: "bannerbtn previous-visit-btn" %>
      <% else %>
        <a href="#" class="hollowbtn previous-visit-btn" data-toggle="modal" data-target="#visitsIndexModal<%= visit.restaurant_id %>">My Review</a>
        <%= render partial: 'visits_index_modal', locals: { visit: visit } %>
      <% end %>
    </div>

  </div>
</div>

app/views/visits/_upcoming_visit_card.html.erb
<div class="restaurant_card">
  <div class="restaurant_card_carousel">
    <%= render 'shared/restaurant_carousel_visit', locals: {:visit => visit, :restaurant => restaurant} %>
  </div>
  <div class="restaurant_card_info">

    <div class="restaurant_info_strip">
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    </div>

    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("category.svg") %> <%= restaurant.category %>
      </p>
    </div>

    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("city.svg") %> <%= restaurant.city %> <br>
        <%= image_tag("address.svg") %> <%= restaurant.address %> <br>
        <%= image_tag("people.svg") %> <%= visit.number_of_people %> <br>
        <%= image_tag("calendar.svg") %> <%= visit.date.strftime("%d/%m/%y") %> <br>
      </p>
    </div>

    <div class="buttons-info" style="align-items: center;">
      <%= link_to visits_path, class: "hollowbtn upcoming-visit-btn" do %>
        <i class="fas fa-edit"></i> Change
      <% end %>
      <%= link_to visit_path(visit), method: 'delete', class: "hollowbtn upcoming-visit-btn" do %>
        <i class="fas fa-trash-alt"></i> Cancel
      <% end %>
    </div>
  </div>
</div>

app/views/visits/_visits_index_modal.html.erb
<div class="modal fade" id="visitsIndexModal<%= visit.restaurant_id %>" tabindex="-1" role="dialog" aria-labelledby="visitsIndexModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header d-flex flex-column">
        <h5 class="modal-title " id="visitsIndexModalTitle"> <%= visit.restaurant.name %></h5>
        <div class="modal-review-details">
          <% if visit.reviews.first.nil? %>
          <p>Rating: <%= visit.reviews.first.rating %> | Visited on: <%= visit.date.strftime("%d/%m/%y") %> | Review from: <%= visit.reviews.first.date %></p>
          <% end %>
        </div>
      </div>
      <div class="modal-body" style="font-size: 16px">
        <% if !visit.reviews.first.nil? %>
        <h5>Your review: </h5>
        <br>
        <em>"<%= visit.reviews.first.content %>"</em>
          <div class="star-container d-flex justify-content-center pt-3">
            <br>
            <% count_gold = visit.reviews.first.rating %>
            <% count_grey = (5 - count_gold) %>
            <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
            <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
          </div>
         <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/visits/index.html.erb
<div class="bookmarks-banner" style="background-image: linear-gradient(rgba(20,20,20,0.7),rgba(20,20,20,0.7)), url(https://www.finedininglovers.com/sites/g/files/xknfdk626/files/styles/open_graph_image/public/2019-11/Greenhouse-restaurant---Photo-by-kayleigh-harrington-on-Unsplash.jpg?itok=qEC_b0Cg);">
  <div class="container bookmarks-banner-heading">
    <h3>Foodie Adventures</h3>
    <h5>Keep track of your foodie adventures - see your personal foodie map here!</h5>
  </div>
</div>

<div id="restaurant_index_container">
  <div id="restaurant_index_cards_container">
    <% if @upcoming_visits.any? %>
        <div class="cards-title-meals">
          <h2 class="visits-title">Upcoming Meals</h2>
          <h5 class=visits-title><em>Your next foodie adventures!</em></h5>
        </div>
        <% @upcoming_visits.each do |v| %>
          <%= render 'upcoming_visit_card', visit: v, restaurant: v.restaurant, followings_visits: @followings_visits %>
        <% end %>
      <% else %>
          <div class="cards-title-meals">
            <h2 class="visits-title">No upcoming visits!</h2>
          <h5 class=visits-title><em>Perhaps you could take a look at where your friends have been recently?</em></h5>
          </div>
      <% end %>
      <% if @previous_visits.any? %>
        <div class="cards-title-meals">
          <h2 class=visits-title>Previous Meals</h2>
          <h5 class=visits-title><em>See your past foodie experiences below</em></h5>
        </div>
        <% @previous_visits.each do |v| %>
          <%= render 'previous_visit_card', visit: v, previous_visits: @previous_visits %>
        <% end %>
    <% else %>
        <div class="cards-title-meals">
          <h2 class="visits-title">No previous visits.</h2>
          <h5 class=visits-title><em>Time to book your next foodie experience.</em></h5>
        </div>
    <% end %>
  </div>
  <div id="restaurants_index_map_container" class="map-index">
    <div class="index-map"> <%= render 'shared/map' %> </div>
  </div>

</div>