config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index]

  resources :restaurants, except: [:show]

  resources :restaurants, only: [:show] do
    resources :visits, only: [:create]
    resources :bookmarks, only: [:create]
  end


  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  resources :visits, only: [:update, :destroy]

  resources :users, only: [] do
    resources :follows, only: [:create]
  end

  resources :follows, only: [:index, :destroy]
  resources :bookmarks, only: [:index, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_mangetoo_svg.html.erb
<svg width="520" height="256", viewPort="0 0 120 120" version="1.1" xmins="http://www.w3.org/2000/svg" class="mangetoo_SVG_Grid">
  <polygon class="svg_part_a round" points="480,108 500,88 492,80 488,76 468,80 440,96 360,108 276,108 244,108 192,96 144,80 140,76 116,84 96,104 92,128 112,156 128,176 152,196 184,212 236,224 280,228 328,228 380,220 412,208 444,184 468,148"></polygon>
  <polygon class="svg_part_b round" points="36,28 64,64 92,64 116,56 136,64 148,56 152,64 144,76 116,84 120,100 132,112 128,120 112,104 100,104 92,128 88,136 84,132 80,100 56,72 28,48 24,36"></polygon>
  <ellipse class="svg_part_c round" rx="24" ry="32" cx="160" cy="136"></ellipse>
  <ellipse class="svg_part_d round" rx="24" ry="36" cx="228" cy="156"></ellipse>
  <ellipse class="svg_part_e round" rx="32" ry="36" cx="316" cy="160"></ellipse>
  <ellipse class="svg_part_f round" rx="32" ry="32" cx="408" cy="152"></ellipse>
</svg>

app/views/shared/_map.html.erb
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "MangeToo", root_path, class: "navbar-brand mangetoo-logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Bookmarks", bookmarks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Reviews", reviews_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Visits", visits_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, alt: "Image of user", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "MangeToo_DefaultUserImage.png", alt: "Image of user", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "All Restaurants", restaurants_path, class: "dropdown-item" %>
            <%= link_to "Foodie Network", follows_path, class: "dropdown-item" %>
            <%= link_to "New Restaurant", new_restaurant_path, class: "dropdown-item" %>
            <%= link_to "Update Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_restaurant_card.html.erb
<div class="restaurant_card">
  <div class="restaurant_card_carousel">
    <%= render 'shared/restaurant_carousel', restaurant: restaurant %>
  </div>
  <div class="restaurant_card_info">

    <div class="restaurant_info_strip">
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    </div>
    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("category.svg") %> <%= restaurant.category %>
      </p>
    </div>

    <div class="restaurant_info_strip">
      <p>
        <%= image_tag("city.svg")%> <%= restaurant.city%> <br>
        <%= image_tag("address.svg") %> <%= restaurant.address%> <br>
      </p>
    </div>

    <div class="buttons-info">
      <%= link_to 'See Details', restaurant_path(restaurant), class: 'greenbtn see-details-btn' %>
      <a href="#" class="hollowbtn d-flex justify-content-center align-items-center" data-toggle="modal" data-target="#restaurantModalReviews<%= restaurant.id %>">
        <span>Reviews
          <div class="star-container d-flex justify-content-center align-items-center">
    <!-- getting the average -->
            <% restaurant_visits = @all_visits.select { |av| av.restaurant_id == restaurant.id } %>
            <% restaurant_reviews = [] %>
            <% restaurant_reviews_ratings = [] %>
            <% restaurant_visits.each do |rv| %>
              <% unless rv.reviews.first.nil? %>
                <% restaurant_reviews << rv.reviews.first %>
                <% restaurant_reviews_ratings << rv.reviews.first.rating %>
              <% end %>
            <% end %>
            <% if restaurant_reviews_ratings == [] %>
              <small>No ratings yet!</small>
            <% else %>
              <% total_figure = restaurant_reviews_ratings.sum %>
              <% count = restaurant_reviews_ratings.count %>
              <% count_gold = (total_figure / count).round %>
              <% count_grey = (5 - count_gold) %>
              <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
              <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
            <% end %>
    <!-- getting the average end -->
          </div>
        </span>
      </a>
        <%= render partial: 'reviews_modal', locals: {restaurant: restaurant, followings_visits: @all_visits} %>
    </div>
  </div>
</div>

app/views/shared/_restaurant_carousel.html.erb
<div class="glider-contain">
  <div id="gliderCarousel<%= restaurant.id %>" class="glider" data-id="<%= restaurant.id %>">
        <% if restaurant.photos.attached? %>
            <% restaurant.photos.each_with_index do |photo, i| %>
                <%= cl_image_tag photo.key, class: "main-image d-block w-100" %>
            <% end %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1521017432531-fbd92d768814?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" class="main-image" alt="">
          <img src="https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" class="main-image" alt="">
          <img src="https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1334&q=80" class="main-image" alt="">
        <% end %>
  </div>
  <div role="tablist" id="gliderCarouselDots<%= restaurant.id %>" class="dots"></div>
  <button role="button" aria-label="Previous" id="gliderCarouselPrev<%= restaurant.id %>" class="glider-prev">«</button>
  <button role="button" aria-label="Next" id="gliderCarouselNext<%= restaurant.id %>" class="glider-next">»</button>
</div>

app/views/shared/_restaurant_carousel_visit.html.erb
<div class="glider-contain">
  <div id="gliderCarousel<%= locals[:visit].id %>" class="glider" data-id="<%= locals[:visit].id %>">
        <% if locals[:restaurant].photos.attached? %>
            <% locals[:restaurant].photos.each_with_index do |photo, i| %>
                <%= cl_image_tag photo.key, class: "main-image d-block w-100" %>
            <% end %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1521017432531-fbd92d768814?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" class="main-image" alt="">
          <img src="https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" class="main-image" alt="">
          <img src="https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1334&q=80" class="main-image" alt="">
        <% end %>
  </div>
  <div role="tablist" id="gliderCarouselDots<%= locals[:visit].id %>" class="dots"></div>
  <button role="button" aria-label="Previous" id="gliderCarouselPrev<%= locals[:visit].id %>" class="glider-prev">«</button>
  <button role="button" aria-label="Next" id="gliderCarouselNext<%= locals[:visit].id %>" class="glider-next">»</button>
</div>