config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index]

  resources :restaurants, except: [:show]

  resources :restaurants, only: [:show] do
    resources :visits, only: [:create]
    resources :bookmarks, only: [:create]
  end


  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  resources :visits, only: [:update, :destroy]

  resources :users, only: [] do
    resources :follows, only: [:create]
  end

  resources :follows, only: [:index, :destroy]
  resources :bookmarks, only: [:index, :destroy]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :bookmarks
  has_many :users, through: :bookmarks
  has_many :visits
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews, through: :visits

  include AlgoliaSearch
  algoliasearch do
    attributes :name
    searchableAttributes ['name']
  end

  # UNCOMMENT THE VALIDATIONS BELOW LATER IN THE PROJECT
  # validates :name, presence: true
  # validates :address, presence: true
  # validates :city, presence: true
  # validates :category, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    followings_id = Follow.where(follower_id: current_user.id).map { |user| user.following_id }
    @followings_visits = followings_id.map { |id| Visit.where(user_id: id) }.flatten
    followings_restaurants = @followings_visits.map { |v| v.restaurant.id }
    my_visits = Visit.where(user_id: current_user.id)
    @all_visits = []
    @followings_visits.each { |fv| @all_visits << fv }
    my_visits.each { |mv| @all_visits << mv }
    my_restaurants = my_visits.map { |v| v.restaurant.id }
    all_restaurants_id = my_restaurants | followings_restaurants
    restaurants = all_restaurants_id.map { |id| Restaurant.where(id: id) }.flatten
    restaurants = Restaurant.all

    if params[:query].present?
      @restaurants = restaurants.select { |rest| rest[:city].downcase == params[:query].downcase }
      @city = params[:query].split(" ").map { |w| w.capitalize }.join(" ")
    else
      @restaurants = restaurants
    end
      @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }
    end
    if @restaurants.empty?
      @restaurants = Restaurant.all
      @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }
      end
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant successfully created"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      render :new
    end
  end

  def show
    followings_id = Follow.where(follower_id: current_user.id).map { |user| user.following_id }
    visit_from_followings = followings_id.map { |id| Visit.where(user_id: id, restaurant: @restaurant) }
    visit_ids_from_followings = visit_from_followings.map { |visit| visit.ids }.flatten
    reviews_from_followings = visit_ids_from_followings.map { |id| Review.where(visit_id: id) }.flatten
    my_visits = current_user.visits.where(restaurant_id: params[:id])
    my_reviews = my_visits.map { |v| v.reviews }.flatten.sort_by { |r| r[:created_at]}
    @reviews = (reviews_from_followings + my_reviews).sort_by { |r| r.visit.date }.reverse
    @markers =
      [{
        lat: @restaurant.latitude,
        lng: @restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant })
      }]
    @visit = Visit.new
    user_bookmarks = Bookmark.where(user: current_user)
    @user_bookmarked_restaurants = user_bookmarks.map { |b| b.restaurant }

    # calculating average rating
    if @reviews == []
      @avg_rating = 0
    else
      review_ratings_total = @reviews.map { |r| r.rating }.sum
      review_count = @reviews.count
      @avg_rating = (review_ratings_total / review_count).round
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant successfully updated"
      redirect_to restaurant_path(@restaurant)
    else
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      render :edit
    end
  end

  def destroy
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :category, :website, :phone_number, photos: [])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # def truncate(text, length = 100, truncate_string = "...")
  #   return "No review written." if text.nil?
  #   l = length - truncate_string.chars.to_a.size
  #   (text.chars.to_a.size > length ? text.chars.to_a[0...l].join + truncate_string : text).to_s
  # end
end

app/views/restaurants/_booking_modal.html.erb
<div class="modal fade" id="bookingModal<%= @restaurant.id %>" tabindex="-1" role="dialog" aria-labelledby="bookingModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" id="new-booking-modal-content">
      <div class="modal-header" id="booking-modal-header">
        <h5 class="modal-title" id="bookingModalTitle">Booking for <%= restaurant.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="booking-modal-close-symbol">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="new-booking-form">
          <%= simple_form_for [restaurant, @visit] do |f| %>
          <div class="booking-form-selectors d-flex justify-content-around">
            <div class="booking-form-date-selector d-flex flex-column justify-content-start mb-5">
              <p>Choose a date for your booking:</p>
              <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            </div>
            <br>
            <div class="booking-form-number-foodies-selector d-flex flex-column justify-content-start mb-3">
              <p>Number of foodies:</p>
              <%= f.input :number_of_people, :as => :integer, input_html: { id: "booking-form-foodie-selector" } %>
            </div>
          </div>
          <div id="new-booking-button">
            <%= f.submit "Book", class: "bookingbtngreen", id: "new-booking-form-submit" %>
            <%= link_to "", visits_path, id: "go-to-visits-link", class: "hidden" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_info_window.html.erb
<div class="card">
  <% if restaurant.photos.attached? %>
    <div id="carousel-<%= restaurant.id %>" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% restaurant.photos.each_with_index do |photo, i| %>
          <div class="carousel-item <%= 'active' if i == 0 %>">
            <%= cl_image_tag photo.key, class: "card-img-top d-block w-100" %>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-<%= restaurant.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-<%= restaurant.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% else %>
    <%= image_tag "MangeToo_DefaultUserImage.png", alt: "Image of a mangetout cartoon", class: "card-img-top", style: "height: 150px; object-fit: contain; overflow: hidden" %>
  <% end %>
  <div class="card-body">
    <h5 class="category-tag"> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h5>
    <p class="card-title"><%= restaurant.address %></p>
  </div>
</div>

app/views/restaurants/_reviews_modal.html.erb
<div class="modal fade" id="restaurantModalReviews<%= restaurant.id %>" tabindex="-1" role="dialog" aria-labelledby="restaurantModalReviewsTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="title_and_rating">
          <h5 class="modal-title " id="restaurantModalReviewsTitle"><%= restaurant.name %></h5>
          <div class="star-container" style="margin-right: 10px">
<!-- getting the average -->
              <% restaurant_visits = @all_visits.select { |av| av.restaurant_id == restaurant.id } %>
              <% restaurant_reviews = [] %>
              <% restaurant_reviews_ratings = [] %>
              <% restaurant_visits.each do |rv| %>
                <% unless rv.reviews.first.nil? %>
                  <% restaurant_reviews << rv.reviews.first %>
                  <% restaurant_reviews_ratings << rv.reviews.first.rating %>
                <% end %>
              <% end %>
              <% if restaurant_reviews_ratings == [] %>
                <p>No ratings yet!</p>
              <% else %>
                <% total_figure = restaurant_reviews_ratings.sum %>
                <% count = restaurant_reviews_ratings.count %>
                <% count_gold = (total_figure / count).round %>
                <% count_grey = (5 - count_gold) %>
                <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
                <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
              <% end %>
<!-- getting the average end -->
          </div>
        </div>
        <div class="modal-header d-flex flex-column">
          <p><%= restaurant.address %>, <%= restaurant.city %></p>
          <div class="modal-review-details">
          </div>
        </div>
<!-- modal if there are no reviews-->
        <% if restaurant_reviews == [] %>
          <div class="modal-body" style="font-size: 16px">
            <p>No reviews yet by your Fellow Foodies! Be the first to write one!</p>
          </div>
<!-- modal if there are no reviews end-->
        <% else %>
<!-- modal if there are reviews -->
          <% @all_visits.select { |v| v.restaurant_id == restaurant.id }.each do |v| %>
            <div class="modal-body" style="font-size: 16px">
              <% if !v.reviews.first.nil? %>
                <p> <u> <%= v.user.first_name %> <%= v.user.last_name %></u>. Visited on: <%= v.date.strftime("%d/%m/%y") %> |
                Review from: <%= v.reviews.first.created_at.strftime("%d/%m/%y") %></p>
                <em>"<%= v.reviews.first.content %>"</em>
                <div class="star-container d-flex justify-content-center p-2">
                  <% count_gold = v.reviews.first.rating %>
                  <% count_grey = (5 - count_gold) %>
                  <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
                  <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
                </div>
              <% end %>
            </div>
<!-- modal if there are reviews end -->
          <% end %>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

app/views/restaurants/_show_modal.html.erb
<div class="modal fade" id="reviewShowModal<%= review.id %>" tabindex="-1" role="dialog" aria-labelledby="reviewShowModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header d-flex flex-column">
        <div class="modal-header-and-stars"> <h5 class="modal-title " id="reviewShowModalTitle"><%= review.visit.restaurant.name %> </h5>
          <div class="star-container">
            <% count_gold = review.rating %>
            <% count_grey = (5 - count_gold) %>
            <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
            <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
          </div>
        </div>
        <p><%= review.visit.restaurant.address %>, <%= review.visit.restaurant.city %></p>
        <div class="modal-review-details">
          <p> Visited on: <%= review.visit.date.strftime("%d/%m/%y") %> | Review from: <%= review.created_at.strftime("%d/%m/%y") %></p>
        </div>
      </div>
      <div class="modal-body" style="font-size: 16px">
        <em>"<%= review.content %>"</em>
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Restaurant edit</h1>

<div class="container-form card" >
  <div class="edit_form"> <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name, :as => :string, input_html: { :style=> 'width: 400px;' }%>
    <%= f.input :address, :as => :string, input_html: { :style=> 'width: 400px;' }%>
    <%= f.input :city, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :latitude, :as => :float, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :longitude, :as => :float, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :category, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :website, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :phone_number, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Update Restaurant", class: "bannerbtn", input_html: { :style=> 'padding: 10px;' }%>
  <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="bookmarks-banner" style="background-image: linear-gradient(rgba(20,20,20,0.7),rgba(20,20,20,0.7)), url(https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shinjuku_Restaurant_%28Unsplash%29.jpg/800px-Shinjuku_Restaurant_%28Unsplash%29.jpg);">
  <div class="container bookmarks-banner-heading">
    <% if params[:query].present? %>
      <h3>Restaurants in <%= @city %></h3>
      <h5>See the restaurants in <%= @city %> visited by your Fellow Foodies!</h5>
    <% else %>
      <h3>All Restaurants</h3>
      <h5>See all the restaurants visited by your Fellow Foodies!</h5>
    <% end %>
  </div>
</div>

<div id="restaurant_index_container">

  <div id="restaurant_index_cards_container">
    <% @restaurants.each do |restaurant| %>
      <%= render 'shared/restaurant_card', restaurant: restaurant %>
    <% end %>
  </div>

  <div id="restaurants_index_map_container" class="map-index">
    <div class="index-map"> <%= render 'shared/map' %> </div>
  </div>

</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<div class="container-form" >
  <div id="new-restaurant-form"> <%= simple_form_for(@restaurant, url: restaurants_path) do |f| %>
    <%= f.input :name, :as => :string, input_html: { :style=> 'width: 400px;' }%>
    <div id="name-search-list">
    </div>
    <%= f.input :address, :as => :string %>
    <%= f.input :city, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :category, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :website, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :phone_number, :as => :string, input_html: { :style=> 'width: 400px;' } %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Add Restaurant", class: "bannerbtn" %>
    <% end %>
  </div>
</div>


<%= javascript_pack_tag "algolia" %>

app/views/restaurants/show.html.erb
<div class="container", id="show">

  <div class="row">
    <div class="col-8">
      <div class="photo-carousel" id="show-restaurant-carousel">
        <%= render 'shared/restaurant_carousel', restaurant: @restaurant %>
      </div>

      <div class="card-container-show">
          <% @reviews.each do |review| %>
            <div class="card-show">
              <% if review.visit.user.super_foodie %>
                <div class="avatar-show-superfoodie">
                  <% if review.visit.user.photo.attached? %>
                    <%= cl_image_tag review.visit.user.photo.key, alt: "Image of user" %>
                  <% else %>
                    <%= image_tag(review.visit.user.default_image) %>
                  <% end %>
                </div>
              <% else %>
                <div class="avatar-show">
                  <% if review.visit.user.photo.attached? %>
                    <%= cl_image_tag review.visit.user.photo.key, alt: "Image of user" %>
                  <% else %>
                    <%=image_tag(review.visit.user.default_image)%>
                  <% end %>
                </div>
              <% end %>
                <div class="card-show-infos">
                  <div class="name_date_flex-show">
                    <% if review.visit.user.super_foodie %>
                      <div class="name-mangetoo d-flex">
                        <h2> <%= review.visit.user.first_name + " " + review.visit.user.last_name %> </h2>
                        <%= image_tag("MangeToo_MapMarker.png") %>
                      </div>
                    <% else %>
                      <h2> <%= review.visit.user.first_name + " " + review.visit.user.last_name %> </h2>
                    <% end %>
                    <div class="star-container">
                      <% count_gold = review.rating %>
                      <% count_grey = (5 - count_gold) %>
                      <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
                      <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
                    </div>
                  </div>
                  <p><em>"<%= review.content.truncate(100) %>"</em><a href="#" class="see_more_btn" data-toggle="modal" data-target="#reviewShowModal<%= review.id %>"> See More</a>
                  <%= render partial: 'show_modal', locals: {review: review} %></p>
                  <p class = "show-review-date"> Review date: <%= review.visit.date.strftime("%d/%m/%y") %></p>
                </div>
            </div>
          <% end %>
      </div>
    </div>

    <div class="col-4">
      <div class="restaurant-info">
        <h2><%= @restaurant.name %></h2>
        <% if @avg_rating == 0 %>
          <p>No ratings yet!</p>
        <% else %>
          <% count_gold = @avg_rating %>
          <% count_grey = (5 - count_gold) %>
          <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
          <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
        <% end %>
        <div class="content-info">
          <p><%= image_tag("greenlocation.svg") %> <%= @restaurant.address %></p>
          <p><%= image_tag("greencategory.svg") %> <%= @restaurant.category %></p>
        </div>
        <div class="content-info">
          <p><%= image_tag("greenwebsite.svg") %><a href="http://<% @restaurant.website %>" target="_blank"><%= @restaurant.website %></a></p>
          <p><%= image_tag("greenphone.svg") %> <%= @restaurant.phone_number %></p>
        </div>
        <div class="buttons-info">
          <div class="book-button-container">
            <button type="button" class="showgreenbtn" data-toggle="modal" data-target="#bookingModal<%= @restaurant.id %>">
              Book
            </button>
          </div>
          <%= render partial: 'booking_modal', locals: {restaurant: @restaurant} %>
          <div class="bookmark-button-container d-flex">
            <%= render 'bookmarks/bookmark_button', restaurant: @restaurant, user_bookmarked_restaurants: @user_bookmarked_restaurants %>
          </div>
        </div>
      </div>
        <div
          id="map"
          style="width: 100%;
          height: 400px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
        <% if current_user.admin %>
          <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), style: "color: white" %>
        <% end %>
    </div>
  </div>