config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index]

  resources :restaurants, except: [:show]

  resources :restaurants, only: [:show] do
    resources :visits, only: [:create]
    resources :bookmarks, only: [:create]
  end


  resources :visits, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  resources :visits, only: [:update, :destroy]

  resources :users, only: [] do
    resources :follows, only: [:create]
  end

  resources :follows, only: [:index, :destroy]
  resources :bookmarks, only: [:index, :destroy]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews_array = []
    reviews = current_user.reviews.sort_by { |r| r[:created_at] }.reverse
    reviews.each do |review|
      visit = Visit.find(review.visit_id)
      restaurant = Restaurant.find(visit.restaurant_id)
      index_hash = {
        review_content_truncated: truncate(review.content),
        review_id: review.id,
        review_content: review.content,
        review_rating: review.rating,
        review_date: review.created_at.strftime("%d/%m/%y"),
        visit_date: visit.date.strftime("%d/%m/%y"),
        visit_num_of_people: visit.number_of_people,
        restaurant_instance: restaurant,
        restaurant_name: restaurant.name,
        restaurant_address: restaurant.address,
        restaurant_city: restaurant.city
      }
      @reviews_array << index_hash
    end
    @restaurants = []
    @reviews_array.map do |review_hash|
      @restaurants << review_hash[:restaurant_instance]
    end
    @reviews_array.sort_by { |r| r[:review_date] }.reverse

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "restaurants/info_window", locals: { restaurant: restaurant }),
      }
    end
  end

  def new
    @visit = Visit.find(params[:visit_id])
    @restaurant = Restaurant.find(@visit.restaurant_id)
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @visit = Visit.find(params[:visit_id])
    @review.visit = @visit
    if @review.save
      flash[:notice] = "Thank you for your review!"
      redirect_to reviews_path
    else
      raise
      flash[:notice] = "Sorry, an error has occurred. Please try again later or contact the MangeToo team."
      redirect_to visits_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:visit_id, :content, :rating)
  end

  def truncate(text, length = 100, truncate_string = "...")
    return "No review written." if text.nil?
    l = length - truncate_string.chars.to_a.size
    (text.chars.to_a.size > length ? text.chars.to_a[0...l].join + truncate_string : text).to_s
  end
end

app/views/reviews/_index_modal.html.erb
<div class="modal fade" id="reviewIndexModal<%= review_hash[:review_id] %>" tabindex="-1" role="dialog" aria-labelledby="reviewIndexModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="title_and_rating">
        <div class="modal-header-and-stars"> <h5 class="modal-title " id="reviewIndexModalTitle"><%= review_hash[:restaurant_name] %></h5>
          <div class="star-container">
            <% count_gold = review_hash[:review_rating] %>
            <% count_grey = (5 - count_gold) %>
            <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
            <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
          </div>
        </div>
      </div>
      <div class="modal-header d-flex flex-column">
        <p><%= review_hash[:restaurant_address] %>, <%= review_hash[:restaurant_city] %></p>
        <div class="modal-review-details">
          <p>Visited on: <%= review_hash[:visit_date] %> | Review from: <%= review_hash[:review_date] %></p>
        </div>
      </div>
      <div class="modal-body" style="font-size: 16px">
       <em>"<%= review_hash[:review_content] %>"</em>
      </div>
      <div class="modal-footer">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="bookmarks-banner" style="background-image: linear-gradient(rgba(20,20,20,0.7),rgba(20,20,20,0.7)), url(https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shinjuku_Restaurant_%28Unsplash%29.jpg/800px-Shinjuku_Restaurant_%28Unsplash%29.jpg);">
  <div class="container bookmarks-banner-heading">
    <h3>Reviewed Restaurants</h3>
    <h5>See all the reviews you have written here!</h5>
  </div>
</div>

<div id="restaurant_index_container">
  <% if @reviews_array.any? %>
    <div id="restaurant_index_cards_container">
      <% @reviews_array.each do |review_hash| %>
        <div class="review-index-card d-flex flex-wrap-reverse flex-sm-nowrap">
          <div class="review-index-card-carousel">
            <%= render 'shared/restaurant_carousel', restaurant: review_hash[:restaurant_instance] %>
          </div>
          <div class="review-body">
            <div class="restaurant_info_strip">
              <h2 style="margin-bottom: 3px;"><%= link_to review_hash[:restaurant_name], restaurant_path(review_hash[:restaurant_instance]) %></h2>
            </div>
            <div class="restaurant_info_strip">
              <p style="margin-left: 0px; margin-bottom: 5px; margin-top: 0;"> <%= image_tag("city.svg")%> <%= review_hash[:restaurant_city] %></p>
            </div>
            <p class="review-details" style="margin-bottom: 7px;">Visited on: <%= review_hash[:visit_date] %> | Review from: <%= review_hash[:review_date] %></p>
            <div class="star-container" style="text-align: center;margin-bottom:10px;">
              <% count_gold = review_hash[:review_rating] %>
              <% count_grey = (5 - count_gold) %>
              <% count_gold.times do %> <i class="fas fa-star gold-star"></i> <% end %>
              <% count_grey.times do %> <i class="fas fa-star grey-star"></i> <% end %>
            </div>
            <p style="font-size: 13px;"><em>"<%= review_hash[:review_content_truncated] %>"</em>
              <a href="#" class="see_more_btn" data-toggle="modal" data-target="#reviewIndexModal<%= review_hash[:review_id] %>">See More</a>
              <%= render partial: 'index_modal', locals: {review_hash: review_hash} %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div id="restaurant_index_cards_container">
      <div class="cards-title-meals">
        <h2 class="visits-title">No reviews yet.</h2>
        <h5 class=visits-title>Rate your latest foodie experiences and leave a review. They will appear <b>here</b> and at your foodies friends dashboard.</h5>
      </div>
    </div>
  <% end %>

  <div id="restaurants_index_map_container" class="map-index">
    <div class="index-map"> <%= render 'shared/map' %> </div>
  </div>

</div>

app/views/reviews/new.html.erb
<!-- <div class="d-flex align-items-center justify-content-space-between"> -->
  <div class = "new-review-flexbox">
  <div class = "photo-carousel new-review-carousel">
    <%= render 'shared/restaurant_carousel', restaurant: @restaurant %>
  </div>
  <div class="review-form-container d-flex flex-column">
    <h3 class="review-form-header">Write your review of <%= @restaurant.name %> below:</h3>
    <br>
    <div id="new-review-form">
      <%= simple_form_for(@review, url: visit_reviews_path(@visit)) do |f| %>
        <div id = "new-review-input">
          <%= f.input :content, :as => :text, placeholder: "Write your review here...", input_html: { class: "content-form" } %>
        </div>
        <div class="rating-select d-flex justify-content-space-between">
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        </div>
        <%= f.submit "Add Review", class: "bannerbtn" %>
      <% end %>
    </div>
  </div>
</div>